linux: #Группа хостов
  children: #Обозначение, что будет подгруппа хостов
    nginx: #Имя подгруппы хостов
      hosts: #Узлы группы
        <Имя ВМ>:
          ansible_host: <public ip-адрес ВМ>
        <Имя ВМ>:
          ansible_host: <public ip-адрес ВМ>
        <Имя ВМ>:
          ansible_host: <public ip-адрес ВМ>
  vars: #Переменные, доступные или используемые для всех подгрупп
    ansible_user: "YOUR_USER"
    ansible_password: "YOUR_PASSWORD"
    connection_protocol: ssh #тип подключения
    ansible_become: false #Становиться ли другим пользователем после подключения
